#!/usr/bin/env bash
# Point local development at the SAME cloud databases production uses.
# After this, `uvicorn api.main:app --reload` reads/writes Supabase + Aura —
# not the Docker postgres/neo4j/milvus stack.
#
# Usage:
#   bash deploy/free/link-local-env.sh
#
# Requires deploy/free/credentials.env (copy from credentials.env.example).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
CREDS="$ROOT/deploy/free/credentials.env"
ENV_FILE="$ROOT/.env"

if [[ ! -f "$CREDS" ]]; then
  echo "Missing $CREDS" >&2
  echo "  cp deploy/free/credentials.env.example deploy/free/credentials.env" >&2
  echo "  # fill in DATABASE_URL, NEO4J_URI, NEO4J_PASSWORD" >&2
  exit 1
fi

python3 - "$CREDS" "$ENV_FILE" << 'PY'
import sys
from pathlib import Path

creds_path = Path(sys.argv[1])
env_path   = Path(sys.argv[2])

def parse_env(path: Path) -> dict[str, str]:
    out: dict[str, str] = {}
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, v = line.split("=", 1)
        out[k.strip()] = v.strip()
    return out

c = parse_env(creds_path)
required = ["DATABASE_URL", "NEO4J_URI", "NEO4J_PASSWORD"]
missing = [k for k in required if not c.get(k)]
if missing:
    raise SystemExit(f"Missing in {creds_path}: {', '.join(missing)}")

lines = [
    "# Generated by deploy/free/link-local-env.sh",
    "# Local uvicorn uses the SAME Supabase + Neo4j Aura as production.",
    "# Re-run this script after rotating cloud credentials.",
    "",
    f"DATABASE_URL={c['DATABASE_URL']}",
    "VECTOR_BACKEND=pgvector",
    "POSTGRES_SSLMODE=require",
    "",
    f"NEO4J_URI={c['NEO4J_URI']}",
    f"NEO4J_USER={c.get('NEO4J_USER', 'neo4j')}",
    f"NEO4J_PASSWORD={c['NEO4J_PASSWORD']}",
    "",
    "# Scoring defaults (match production / fly.toml)",
    "ALPHA=0.4",
    "ALPHA_LEX=0.3",
    "ALPHA_SEM=0.5",
    "ALPHA_CAT=0.2",
    "DIRICHLET_MU=2000",
    "MIN_SCORE=0.55",
    "",
    "SCINCL_MODEL=malteos/scincl",
    "SCINCL_CACHE_DIR=./.model_cache",
]

if c.get("GEMINI_API_KEY"):
    lines += ["", f"GEMINI_API_KEY={c['GEMINI_API_KEY']}"]

env_path.write_text("\n".join(lines) + "\n")
print(f"✓ Wrote {env_path}")
print("  Local dev now targets Supabase + Neo4j Aura (same as production).")
print("  Start:  uvicorn api.main:app --host 0.0.0.0 --port 8080 --reload")
PY
